"""Step 4: have Agda check the raw certificates emitted by the pipeline.

    python pipeline/check_agda.py results/pipeline_items.jsonl --agda /path/to/agda

Writes agda/src/Metonymy/ConMeCBatch.agda (generated, not tracked) with one claim per certificate:
    tag (C.check (C.resolve raw)) ≡ 1     for a Resolve certificate that must be accepted,
    tag (C.check (C.retain raw))  ≡ 2     for a Retain certificate that must be accepted,
    tag (C.check ...)             ≡ 0     for a deliberately corrupted control that must be rejected,
and a final `C.acceptAll batch ≡ true` over the accepted ones. Agda is run on the file; when a claim fails the
claim is dropped, recorded, and Agda is re-run, so the output is a per-certificate account.
Acceptance is against the uniform snapshot of Metonymy.ConMeCSnap: it certifies the type and route structure of
the certificate against the lexicon, not the truth of the sentence.
"""
import argparse
import json
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import lexicon  # noqa: E402

MOD = "ConMeC"
MODULE = "Metonymy.ConMeCBatch"
PATH = os.path.join(HERE, "..", "agda", "src", "Metonymy", "ConMeCBatch.agda")
LEXICONS = {"ConMeC": os.path.join(HERE, "..", "lexicon", "conmec_v1.json"), "Toponym": os.path.join(HERE, "..", "lexicon", "toponym_v1.json")}
AGDA_DIR = os.path.join(HERE, "..", "agda")


def nat_list(xs):
    return "(" + " ∷ ".join([str(x) for x in xs] + ["[]"]) + ")"


def raw(c):
    return "(Ev.rawResolve (rawCert %d (rawArg %d %s ∷ [])) %s)" % (c["pred"], c["const"], nat_list(c["route"]), nat_list(c["refs"]))


def claim(name, c, expect):
    ctor = {"resolve": "C.resolve", "retain": "C.retain"}[c["mode"]]
    return "%s : tag (C.check (%s %s)) ≡ %d\n%s = refl" % (name, ctor, raw(c), expect, name)


def controls(lx, item, k):
    """One corrupted variant of the item's certificate, with the reason it must be rejected."""
    c = dict(item["cert"])
    kinds = ["type clash (coerced sort, no coercion applied)", "wrong coercion for the sort",
             "unknown constant identifier", "unknown predicate identifier", "referent outside the snapshot"]
    kind = kinds[k % len(kinds)]
    cat = item["category"]
    lit = lx.literal_sort(cat)
    tgt = next(e["tgt"] for e in lx.edges if e["src"] == lit)
    if k % 5 == 0:
        c.update(pred=lx.pred_id["ctx" + tgt], route=[])
    elif k % 5 == 1:
        other = next(e for e in lx.edges if e["src"] != lit)
        c.update(pred=lx.pred_id["ctx" + other["tgt"]], route=[lx.edge_id[other["name"]]])
    elif k % 5 == 2:
        c.update(const=len(lx.constants) + 3)
    elif k % 5 == 3:
        c.update(pred=len(lx.predicates) + 3)
    else:
        c.update(refs=[1])
    c["mode"] = "resolve"
    return kind, c


def toponym_controls(lx, item, k):
    """Corrupted variants of a toponym certificate (needs item['ctl'] from layer.py)."""
    c = dict(item["cert"])
    ctl = item["ctl"]
    kinds = ["type clash (coerced sort, no coercion applied)", "referent not related to the place in the KB",
             "KB has no such institution for the place", "unknown constant identifier", "unknown predicate identifier"]
    kind = kinds[k % 5]
    if k % 5 == 0:
        if not c["route"]:
            return None          # the certificate has no coercion to drop
        c.update(route=[])
    elif k % 5 == 1:
        if ctl.get("wrong_ref") is None:
            return None
        c.update(refs=[ctl["wrong_ref"]])
    elif k % 5 == 2:
        if ctl.get("empty_place") is None:
            return None
        c.update(const=ctl["empty_place"])
    elif k % 5 == 3:
        c.update(const=ctl["n_places"] + 3)
    else:
        c.update(pred=len(lx.predicates) + 3)
    c["mode"] = "resolve"
    return kind, c


def write_module(claims, accepted):
    L = ["{-# OPTIONS --safe --cubical --guardedness -WnoUnsupportedIndexedMatch #-}", "",
         "-- GENERATED by pipeline/check_agda.py. Do not edit by hand.", "module %s where" % MODULE, "",
         "open import Cubical.Foundations.Prelude", "open import Cubical.Data.Nat using (ℕ ; zero ; suc)",
         "open import Cubical.Data.Bool using (Bool ; true ; false)",
         "open import Cubical.Data.List using (List ; [] ; _∷_)", "",
         "open import Metonymy.%sKB hiding (Fin)" % MOD, "open import Metonymy.Check", "open import Metonymy.%sSnap" % MOD,
         "import Metonymy.Evidence L R as Ev", "", "-- One claim per certificate."]
    L += claims
    L += ["", "-- The whole batch of accepted certificates, by computation.", "batch : C.acceptAll", "  ( " +
          "\n  ∷ ".join(accepted + ["[]"]) + " ) ≡ true", "batch = refl"]
    with open(PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")


def run_agda(agda):
    t = time.time()
    p = subprocess.run([agda, "--transliterate", "src/Metonymy/%sBatch.agda" % MOD], cwd=AGDA_DIR,
                       capture_output=True, text=True, encoding="utf-8", errors="replace")
    return p.returncode, p.stdout + p.stderr, time.time() - t


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("items")
    ap.add_argument("--agda", default="agda")
    ap.add_argument("--controls", type=int, default=50)
    ap.add_argument("--space", default="ConMeC", choices=["ConMeC", "Toponym"])
    a = ap.parse_args()

    global MOD, MODULE, PATH
    MOD = a.space
    MODULE = "Metonymy.%sBatch" % MOD
    PATH = os.path.join(HERE, "..", "agda", "src", "Metonymy", "%sBatch.agda" % MOD)
    lx = lexicon.load(LEXICONS[MOD])
    items = [json.loads(l) for l in open(a.items, encoding="utf-8")]
    items = [it for it in items if "cert" in it]
    ctl_fn = toponym_controls if MOD == "Toponym" else controls
    entries = []   # (name, kind, cert, expect)
    for i, it in enumerate(items):
        entries.append(("ok-%s" % it["id"], it["cert"]["mode"], it["cert"], 1 if it["cert"]["mode"] == "resolve" else 2))
    made, k = 0, 0
    while made < a.controls and k < 20 * a.controls:
        it = items[k % len(items)]
        res = ctl_fn(lx, it, k)
        if res:
            entries.append(("bad-%d-%s" % (made, it["id"]), res[0], res[1], 0))
            made += 1
        k += 1

    dropped = {}
    total_time = 0.0
    for attempt in range(40):
        live = [e for e in entries if e[0] not in dropped]
        claims = [claim(n, c, ex) for n, _, c, ex in live]
        accepted = ["C.%s %s" % ({"resolve": "resolve", "retain": "retain"}[c["mode"]], raw(c)) for n, _, c, ex in live if ex > 0]
        write_module(claims, accepted)
        rc, out, dt = run_agda(a.agda)
        total_time += dt
        if rc == 0:
            break
        m = re.search(r"Batch\.agda:(\d+)\.", out)
        line = int(m.group(1)) if m else None
        txt = open(PATH, encoding="utf-8").read().splitlines()
        name = txt[line - 1].split(" ")[0] if line and line <= len(txt) else None
        if name and any(e[0] == name for e in live):
            dropped[name] = out.strip().splitlines()[1:3]
        else:
            print("Agda failed outside a claim:\n" + out[:1500])
            sys.exit(1)

    ok = [e for e in entries if e[3] > 0]
    bad = [e for e in entries if e[3] == 0]
    ok_dropped = [e for e in ok if e[0] in dropped]
    bad_dropped = [e for e in bad if e[0] in dropped]
    print("Agda %s, %d runs, %.1f s total" % ("accepted the final batch" if rc == 0 else "FAILED", attempt + 1, total_time))
    print("pipeline certificates: %d/%d accepted" % (len(ok) - len(ok_dropped), len(ok)))
    by = {}
    for n, kind, c, ex in bad:
        by.setdefault(kind, [0, 0])
        by[kind][1] += 1
        by[kind][0] += 0 if n in dropped else 1
    print("controls rejected as expected: %d/%d" % (len(bad) - len(bad_dropped), len(bad)))
    for kind, (r, t) in sorted(by.items()):
        print("   %-48s %d/%d" % (kind, r, t))
    if ok_dropped:
        print("unexpectedly rejected pipeline certificates:", [e[0] for e in ok_dropped][:10])
    return 0 if not ok_dropped and not bad_dropped and rc == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
