"""Generate the Agda lexicon module and the uniform snapshot module from lexicon/conmec_v1.json.

    python pipeline/gen_agda.py            # writes agda/src/Metonymy/ConMeCKB.agda and ConMeCSnap.agda

The lexicon module follows the pattern of Metonymy.ExampleKB: sorts, edges, predicates and constants are
enumerations; the raw identifiers carried by certificates are the positions in the JSON lists, and the
name/identifier correspondence proofs required by Metonymy.Check.Lexicon are generated clause by clause.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lexicon import load  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "agda", "src", "Metonymy")


FIN_BLOCK = """
-- Constants are the places of the knowledge-base snapshot, numbered 0 .. NCONST-1.
data Fin : ℕ → Set where
  fz : ∀ {n} → Fin (suc n)
  fs : ∀ {n} → Fin n → Fin (suc n)

toNat : ∀ {n} → Fin n → ℕ
toNat fz     = 0
toNat (fs i) = suc (toNat i)

ofNat : (n : ℕ) → ℕ → Maybe (Fin n)
ofNat zero    _       = nothing
ofNat (suc n) zero    = just fz
ofNat (suc n) (suc m) = mapMaybe fs (ofNat n m)

ofNat-toNat : ∀ {n} (i : Fin n) → ofNat n (toNat i) ≡ just i
ofNat-toNat fz     = refl
ofNat-toNat (fs i) = cong (mapMaybe fs) (ofNat-toNat i)

predℕ : ℕ → ℕ
predℕ zero    = zero
predℕ (suc n) = n

ofNat-sound : ∀ n m (i : Fin n) → ofNat n m ≡ just i → toNat i ≡ m
ofNat-sound zero    m i ()
ofNat-sound (suc n) zero    fz     p = refl
ofNat-sound (suc n) zero    (fs i) ()
ofNat-sound (suc n) (suc m) fz     p with mapMaybe-just fs (ofNat n m) p
... | x , q , ()
ofNat-sound (suc n) (suc m) (fs i) p with mapMaybe-just fs (ofNat n m) p
... | x , q , r = cong suc (trans (sym (cong predℕ (cong toNat r))) (ofNat-sound n m x q))
"""


def nat(n):
    return "zero" if n == 0 else "(suc %s)" % nat(n - 1)


def nat_pat(n, tail="_"):
    s = tail
    for _ in range(n):
        s = "(suc %s)" % s
    return s


def lexicon_module(lx, mod="ConMeC", nconst=None):
    S = lx.sorts
    E = ["e-" + e["name"] for e in lx.edges]
    P = ["p-" + p["name"] for p in lx.predicates]
    K = ["c-" + c["name"] for c in lx.constants]
    numeric = lx.numeric_sort is not None
    L = []
    w = L.append
    w("{-# OPTIONS --safe --cubical-compatible%s #-}" % (" -WnoUnsupportedIndexedMatch" if lx.numeric_sort else ""))
    w("")
    w("-- GENERATED by pipeline/gen_agda.py from the lexicon JSON (%s). Do not edit by hand." % lx.name)
    w("-- The %s lexicon: %d sorts, %d coercion edges, %d predicates, %d constants, no declared equivalences." % (lx.name, len(S), len(E), len(P), len(K)))
    w("module Metonymy.%sKB where" % mod)
    w("")
    w("open import Metonymy.Base")
    w("open import Metonymy.Graph")
    w("open import Metonymy.Check")
    w("")
    w("data T : Set where %s : T" % " ".join(S))
    w("data E : Set where %s : E" % " ".join(E))
    w("data P : Set where %s : P" % " ".join(P))
    if numeric:
        L.extend(FIN_BLOCK.replace("NCONST", str(nconst)).splitlines())
    else:
        w("data K : Set where %s : K" % " ".join(K))
    w("data Ru : Set where")
    w("")
    w("tyEqT : (X Y : T) → Dec (X ≡ Y)")
    for a in S:
        for b in S:
            w("tyEqT %s %s = %s" % (a, b, "yes refl" if a == b else "no (λ ())"))
    w("")
    w("tyEqT-refl : ∀ X → tyEqT X X ≡ yes refl")
    for a in S:
        w("tyEqT-refl %s = refl" % a)
    w("")
    w("G : Graph")
    w("G = record")
    w("  { Ty     = T")
    w("  ; EdgeId = E")
    w("  ; src    = λ { %s }" % "; ".join("%s → %s" % (E[i], e["src"]) for i, e in enumerate(lx.edges)))
    w("  ; tgt    = λ { %s }" % "; ".join("%s → %s" % (E[i], e["tgt"]) for i, e in enumerate(lx.edges)))
    w("  }")
    w("")

    def table(names, pref, idf, namef, ofn, soundn, namen):
        n = len(names)
        out = []
        of = "; ".join(["%s → just %s" % (nat_pat(i, "zero") if False else nat(i), names[i]) for i in range(n)] + ["%s → nothing" % nat_pat(n, "_")])
        out.append("  ; %-14s = λ { %s }" % (ofn, of))
        out.append("  ; %-14s = λ { %s }" % (namef, "; ".join("%s → %d" % (names[i], i) for i in range(n))))
        out.append("  ; %-14s = λ { %s }" % (namen, "; ".join("%s → refl" % names[i] for i in range(n))))
        clauses = []
        for i in range(n):
            for j in range(n):
                clauses.append("%s %s %s → refl" % (nat(i), names[j], "_") if i == j else "%s %s ()" % (nat(i), names[j]))
        # the catch-all index
        for j in range(n):
            clauses.append("%s %s ()" % (nat_pat(n, "k"), names[j]))
        out.append("  ; %-14s = λ { %s }" % (soundn, "\n                      ; ".join(clauses)))
        return out

    w("L : Lexicon")
    w("L = record")
    w("  { graph         = G")
    w("  ; tyEq          = tyEqT")
    w("  ; tyEq-refl     = tyEqT-refl")
    w("  ; PredId        = P")
    w("  ; ConstId       = %s" % ("Fin NCONST".replace("NCONST", str(nconst)) if numeric else "K"))
    w("  ; psig          = λ { %s }" % "; ".join("%s → %s" % (P[i], " ∷ ".join(p["sig"] + ["[]"])) for i, p in enumerate(lx.predicates)))
    if numeric:
        w("  ; cty           = λ _ → %s" % lx.numeric_sort)
    else:
        w("  ; cty           = λ { %s }" % "; ".join("%s → %s" % (K[i], c["sort"]) for i, c in enumerate(lx.constants)))
    for line in table(E, "e", None, "edgeName", "edgeOf", "edgeOf-sound", "edgeOf-name"):
        w(line)
    for line in table(P, "p", None, "predName", "predOf", "predOf-sound", "predOf-name"):
        w(line)
    if numeric:
        w("  ; constOf       = ofNat %d" % nconst)
        w("  ; constName     = toNat")
        w("  ; constOf-name  = ofNat-toNat")
        w("  ; constOf-sound = ofNat-sound %d" % nconst)
    else:
        for line in table(K, "c", None, "constName", "constOf", "constOf-sound", "constOf-name"):
            w(line)
    w("  }")
    w("")
    w("open Routes G")
    w("")
    w("-- No declared equivalences in v1: the rule set is empty.")
    w("R : Rules G")
    w("R = record")
    w("  { RuleId = Ru")
    w("  ; rsrc   = λ ()")
    w("  ; rtgt   = λ ()")
    w("  ; lhs    = λ ()")
    w("  ; rhs    = λ ()")
    w("  }")
    w("")
    w("ruleOfN : ℕ → Maybe Ru")
    w("ruleOfN _ = nothing")
    return "\n".join(L) + "\n"


def snapshot_module(lx):
    L = []
    w = L.append
    w("{-# OPTIONS --safe --cubical --guardedness -WnoUnsupportedIndexedMatch #-}")
    w("")
    w("-- GENERATED by pipeline/gen_agda.py. Do not edit by hand.")
    w("-- The uniform one-element snapshot for ConMeC: every sort has one element, every coercion relates it to")
    w("-- itself and every unary predicate holds of it. Acceptance against this snapshot checks the type and")
    w("-- route structure of a certificate against the lexicon, NOT the truth of the sentence (no external KB).")
    w("module Metonymy.ConMeCSnap where")
    w("")
    w("open import Cubical.Foundations.Prelude")
    w("open import Cubical.Data.Nat using (ℕ ; zero ; suc)")
    w("open import Cubical.Data.Bool using (Bool ; true ; false)")
    w("import Cubical.Data.FinData as F")
    w("open import Cubical.Data.FinData using (Fin ; discreteFin)")
    w("open import Cubical.Data.List using (List ; [] ; _∷_ ; map)")
    w("open import Cubical.Data.Sigma")
    w("import Cubical.Data.Empty as E")
    w("open import Agda.Builtin.Maybe")
    w("")
    w("open import Metonymy.ConMeCKB")
    w("open import Metonymy.Check")
    w("open import Metonymy.Audit G R")
    w("open import Metonymy.Semantics G R using (SoundRules)")
    w("import Metonymy.Evidence L R as Ev")
    w("import Metonymy.Cert L R ruleOfN as Ct")
    w("import Metonymy.NormalizeFull L R as NF")
    w("")
    w("sz : T → ℕ")
    w("sz _ = 1")
    w("")
    w("allFin : (n : ℕ) → List (Fin n)")
    w("allFin zero    = []")
    w("allFin (suc n) = F.zero ∷ map F.suc (allFin n)")
    w("")
    w("private")
    w("  memMap : ∀ {n} {xs : List (Fin n)} {x : Fin n} → Mem x xs → Mem (F.suc x) (map F.suc xs)")
    w("  memMap here      = here")
    w("  memMap (there m) = there (memMap m)")
    w("")
    w("allFin-complete : ∀ n (x : Fin n) → Mem x (allFin n)")
    w("allFin-complete zero    ()")
    w("allFin-complete (suc n) F.zero    = here")
    w("allFin-complete (suc n) (F.suc x) = there (memMap (allFin-complete n x))")
    w("")
    w("fin : FinModel")
    w("fin = record")
    w("  { Elem           = λ A → Fin (sz A)")
    w("  ; elemEq         = λ A → discreteFin")
    w("  ; elems          = λ A → allFin (sz A)")
    w("  ; elems-complete = λ A x → allFin-complete (sz A) x")
    w("  ; tab            = λ e x y → true")
    w("  }")
    w("")
    w("sr : SoundRules (toModel fin)")
    w("sr = audit-all fin (λ ())")
    w("")
    w("kb : Ev.KB")
    w("kb = record")
    w("  { fin      = fin")
    w("  ; refC     = λ c → F.zero")
    w("  ; predTab  = λ p args → true")
    w("  ; unaryTab = λ p A y → true")
    w("  }")
    w("")
    w("ne : ∀ ρ → NF.lhsN ρ ≡ [] → E.⊥")
    w("ne ()")
    w("")
    w("module C = Ct.Cert kb sr ne")
    w("")
    w("tag : Maybe C.Checked → ℕ")
    w("tag nothing                = 0")
    w("tag (just (C.cResolve _))  = 1")
    w("tag (just (C.cRetain _))   = 2")
    w("tag (just (C.cFamily _))   = 3")
    w("tag (just (C.cConjoin _))  = 4")
    w("tag (just (C.cThree _))    = 5")
    return "\n".join(L) + "\n"


def main():
    if len(sys.argv) > 2:
        # python gen_agda.py lexicon/toponym_v1.json Toponym : only the lexicon module
        lx = load(sys.argv[1])
        mod = sys.argv[2]
        nconst = int(sys.argv[3]) if len(sys.argv) > 3 else None
        pairs = ((mod + "KB.agda", lexicon_module(lx, mod, nconst)),)
    else:
        lx = load()
        pairs = (("ConMeCKB.agda", lexicon_module(lx)), ("ConMeCSnap.agda", snapshot_module(lx)))
    for name, text in pairs:
        with open(os.path.join(OUT, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote", name, len(text.splitlines()), "lines")


if __name__ == "__main__":
    main()
