"""The knowledge-base snapshot for toponyms, built from the cached Wikidata facts.

    python pipeline/kbsnap.py        # writes data/kb/snapshot.json, ToponymKB.agda and ToponymSnap.agda

One global snapshot: Place elements are the linked places (the constants of the lexicon are their indices), Polity elements
are the executive and legislative bodies, Team elements the sports teams, People elements one population per place.
Relations: exec/legis/team from Wikidata (P208, P194, P1532/P159), pop is the identity on places. The snapshot has no
declared equivalences to audit, so its size is not limited by the audit cost.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_agda  # noqa: E402
import lexicon  # noqa: E402

KB = os.path.join(HERE, "..", "data", "kb")
AGDA = os.path.join(HERE, "..", "agda", "src", "Metonymy")
LEX = os.path.join(HERE, "..", "lexicon", "toponym_v1.json")
MAX_TEAMS = 6


def build():
    chosen = json.load(open(os.path.join(KB, "chosen.json"), encoding="utf-8"))
    facts = json.load(open(os.path.join(KB, "facts.json"), encoding="utf-8"))
    places = sorted({q for q in chosen.values() if q})
    pidx = {q: i for i, q in enumerate(places)}
    polities, teams = {}, {}
    rel = {"exec": [], "legis": [], "team": [], "pop": [(i, i) for i in range(len(places))]}
    for q in places:
        f = facts.get(q, {})
        for key, edge in (("executive", "exec"), ("legislative", "legis")):
            for b in f.get(key, []):
                j = polities.setdefault(b["qid"], len(polities))
                rel[edge].append((pidx[q], j))
        seen = set()
        for t in f.get("teams", []):
            if t["qid"] in seen or len(seen) >= MAX_TEAMS:
                continue
            seen.add(t["qid"])
            j = teams.setdefault(t["qid"], len(teams))
            rel["team"].append((pidx[q], j))
    snap = {"places": places, "polities": list(polities), "teams": list(teams), "rel": rel}
    json.dump(snap, open(os.path.join(KB, "snapshot.json"), "w", encoding="utf-8"))
    return snap


HEADER = """{-# OPTIONS --safe --cubical --guardedness -WnoUnsupportedIndexedMatch #-}

-- GENERATED by pipeline/kbsnap.py from the cached Wikidata facts. Do not edit by hand.
-- Global snapshot: NPLACES places, NPOL polities, NTEAM teams; relations exec/legis/team from Wikidata, pop identity.
module Metonymy.ToponymSnap where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc)
open import Cubical.Data.Bool using (Bool ; true ; false)
import Cubical.Data.FinData as F
open import Cubical.Data.FinData using (Fin ; discreteFin)
open import Cubical.Data.List using (List ; [] ; _∷_ ; map)
open import Cubical.Data.Sigma
import Cubical.Data.Empty as E
open import Agda.Builtin.Maybe
open import Agda.Builtin.Nat using (_==_)

open import Metonymy.ToponymKB hiding (Fin)
open import Metonymy.Check
open import Metonymy.Audit G R
open import Metonymy.Semantics G R using (SoundRules)
import Metonymy.Evidence L R as Ev
import Metonymy.Cert L R ruleOfN as Ct
import Metonymy.NormalizeFull L R as NF

allFin : (n : ℕ) → List (Fin n)
allFin zero    = []
allFin (suc n) = F.zero ∷ map F.suc (allFin n)

private
  memMap : ∀ {n} {xs : List (Fin n)} {x : Fin n} → Mem x xs → Mem (F.suc x) (map F.suc xs)
  memMap here      = here
  memMap (there m) = there (memMap m)

allFin-complete : ∀ n (x : Fin n) → Mem x (allFin n)
allFin-complete zero    ()
allFin-complete (suc n) F.zero    = here
allFin-complete (suc n) (F.suc x) = there (memMap (allFin-complete n x))

eqℕ : ℕ → ℕ → Bool
eqℕ zero    zero    = true
eqℕ (suc a) (suc b) = eqℕ a b
eqℕ _       _       = false

or : Bool → Bool → Bool
or true  _ = true
or false b = b

and : Bool → Bool → Bool
and true  b = b
and false _ = false

-- Relations are stored as adjacency functions (clauses on numeric literals, then short lists): a lookup is cheap.
lookup : List (ℕ × List ℕ) → ℕ → List ℕ
lookup []             _ = []
lookup ((a , bs) ∷ r) x with a == x
... | true  = bs
... | false = lookup r x

memberℕ : List ℕ → ℕ → Bool
memberℕ []       _ = false
memberℕ (b ∷ bs) y = or (b == y) (memberℕ bs y)

-- The constant with index c refers to the place with index c (every index is below the number of places).
clamp : (n : ℕ) → ℕ → Fin (suc n)
clamp zero    _       = F.zero
clamp (suc n) zero    = F.zero
clamp (suc n) (suc m) = F.suc (clamp n m)

sr : SoundRules (toModel fin)
sr = audit-all fin (λ ())

ne : ∀ ρ → NF.lhsN ρ ≡ [] → E.⊥
ne ()

module C = Ct.Cert kb sr ne

tag : Maybe C.Checked → ℕ
tag nothing                = 0
tag (just (C.cResolve _))  = 1
tag (just (C.cRetain _))   = 2
tag (just (C.cFamily _))   = 3
tag (just (C.cConjoin _))  = 4
tag (just (C.cThree _))    = 5
"""


def snap_module(snap):
    n = len(snap["places"])
    sizes = {"Place": n, "Polity": len(snap["polities"]), "Team": len(snap["teams"]), "People": n}
    head, tail = HEADER.split("sr : SoundRules")
    head = head.replace("NPLACES", str(n)).replace("NPOL", str(sizes["Polity"])).replace("NTEAM", str(sizes["Team"]))
    mid = ["sz : T → ℕ"] + ["sz %s = %d" % (s, k) for s, k in sizes.items()] + [""]
    for e, pairs in snap["rel"].items():
        adj = {}
        for i, j in pairs:
            adj.setdefault(i, []).append(j)
        mid.append("tbl-%s : List (ℕ × List ℕ)" % e)
        mid.append("tbl-%s = %s" % (e, "".join("(%d , %s) ∷ " % (i, " ∷ ".join(str(j) for j in adj[i]) + " ∷ []") for i in sorted(adj)) + "[]"))
        mid.append("")
    mid += ["tbl : E → List (ℕ × List ℕ)"] + ["tbl e-%s = tbl-%s" % (e, e) for e in snap["rel"]]
    mid += ["", "fin : FinModel", "fin = record",
            "  { Elem           = λ A → Fin (sz A)",
            "  ; elemEq         = λ A → discreteFin",
            "  ; elems          = λ A → allFin (sz A)",
            "  ; elems-complete = λ A x → allFin-complete (sz A) x",
            "  ; tab            = λ e x y → memberℕ (lookup (tbl e) (F.toℕ x)) (F.toℕ y)",
            "  }", "",
            "kb : Ev.KB", "kb = record",
            "  { fin      = fin",
            "  ; refC     = λ c → clamp %d (toNat c)" % (n - 1),
            "  ; predTab  = λ p args → true",
            "  ; unaryTab = λ p A y → true",
            "  }", ""]
    return head + "\n".join(mid) + "\nsr : SoundRules" + tail


def main():
    snap = build()
    n = len(snap["places"])
    lx = lexicon.load(LEX)
    open(os.path.join(AGDA, "ToponymKB.agda"), "w", encoding="utf-8", newline="\n").write(gen_agda.lexicon_module(lx, "Toponym", n))
    open(os.path.join(AGDA, "ToponymSnap.agda"), "w", encoding="utf-8", newline="\n").write(snap_module(snap))
    print("places %d, polities %d, teams %d, relation sizes %s" % (n, len(snap["polities"]), len(snap["teams"]), {k: len(v) for k, v in snap["rel"].items()}))


if __name__ == "__main__":
    main()
