{-# OPTIONS --safe --cubical-compatible #-}

-- GENERATED by pipeline/gen_agda.py from the lexicon JSON (ConMeC v1). Do not edit by hand.
-- The ConMeC v1 lexicon: 12 sorts, 6 coercion edges, 12 predicates, 6 constants, no declared equivalences.
module Metonymy.ConMeCKB where

open import Metonymy.Base
open import Metonymy.Graph
open import Metonymy.Check

data T : Set where Container Content Creator Output Product Maker Place LocatedThing Causer Result Possessed Possessor : T
data E : Set where e-contents e-output e-maker e-located e-result e-possessor : E
data P : Set where p-ctxContainer p-ctxContent p-ctxCreator p-ctxOutput p-ctxProduct p-ctxMaker p-ctxPlace p-ctxLocatedThing p-ctxCauser p-ctxResult p-ctxPossessed p-ctxPossessor : P
data K : Set where c-targetContainer c-targetCreator c-targetProduct c-targetPlace c-targetCauser c-targetPossessed : K
data Ru : Set where

tyEqT : (X Y : T) → Dec (X ≡ Y)
tyEqT Container Container = yes refl
tyEqT Container Content = no (λ ())
tyEqT Container Creator = no (λ ())
tyEqT Container Output = no (λ ())
tyEqT Container Product = no (λ ())
tyEqT Container Maker = no (λ ())
tyEqT Container Place = no (λ ())
tyEqT Container LocatedThing = no (λ ())
tyEqT Container Causer = no (λ ())
tyEqT Container Result = no (λ ())
tyEqT Container Possessed = no (λ ())
tyEqT Container Possessor = no (λ ())
tyEqT Content Container = no (λ ())
tyEqT Content Content = yes refl
tyEqT Content Creator = no (λ ())
tyEqT Content Output = no (λ ())
tyEqT Content Product = no (λ ())
tyEqT Content Maker = no (λ ())
tyEqT Content Place = no (λ ())
tyEqT Content LocatedThing = no (λ ())
tyEqT Content Causer = no (λ ())
tyEqT Content Result = no (λ ())
tyEqT Content Possessed = no (λ ())
tyEqT Content Possessor = no (λ ())
tyEqT Creator Container = no (λ ())
tyEqT Creator Content = no (λ ())
tyEqT Creator Creator = yes refl
tyEqT Creator Output = no (λ ())
tyEqT Creator Product = no (λ ())
tyEqT Creator Maker = no (λ ())
tyEqT Creator Place = no (λ ())
tyEqT Creator LocatedThing = no (λ ())
tyEqT Creator Causer = no (λ ())
tyEqT Creator Result = no (λ ())
tyEqT Creator Possessed = no (λ ())
tyEqT Creator Possessor = no (λ ())
tyEqT Output Container = no (λ ())
tyEqT Output Content = no (λ ())
tyEqT Output Creator = no (λ ())
tyEqT Output Output = yes refl
tyEqT Output Product = no (λ ())
tyEqT Output Maker = no (λ ())
tyEqT Output Place = no (λ ())
tyEqT Output LocatedThing = no (λ ())
tyEqT Output Causer = no (λ ())
tyEqT Output Result = no (λ ())
tyEqT Output Possessed = no (λ ())
tyEqT Output Possessor = no (λ ())
tyEqT Product Container = no (λ ())
tyEqT Product Content = no (λ ())
tyEqT Product Creator = no (λ ())
tyEqT Product Output = no (λ ())
tyEqT Product Product = yes refl
tyEqT Product Maker = no (λ ())
tyEqT Product Place = no (λ ())
tyEqT Product LocatedThing = no (λ ())
tyEqT Product Causer = no (λ ())
tyEqT Product Result = no (λ ())
tyEqT Product Possessed = no (λ ())
tyEqT Product Possessor = no (λ ())
tyEqT Maker Container = no (λ ())
tyEqT Maker Content = no (λ ())
tyEqT Maker Creator = no (λ ())
tyEqT Maker Output = no (λ ())
tyEqT Maker Product = no (λ ())
tyEqT Maker Maker = yes refl
tyEqT Maker Place = no (λ ())
tyEqT Maker LocatedThing = no (λ ())
tyEqT Maker Causer = no (λ ())
tyEqT Maker Result = no (λ ())
tyEqT Maker Possessed = no (λ ())
tyEqT Maker Possessor = no (λ ())
tyEqT Place Container = no (λ ())
tyEqT Place Content = no (λ ())
tyEqT Place Creator = no (λ ())
tyEqT Place Output = no (λ ())
tyEqT Place Product = no (λ ())
tyEqT Place Maker = no (λ ())
tyEqT Place Place = yes refl
tyEqT Place LocatedThing = no (λ ())
tyEqT Place Causer = no (λ ())
tyEqT Place Result = no (λ ())
tyEqT Place Possessed = no (λ ())
tyEqT Place Possessor = no (λ ())
tyEqT LocatedThing Container = no (λ ())
tyEqT LocatedThing Content = no (λ ())
tyEqT LocatedThing Creator = no (λ ())
tyEqT LocatedThing Output = no (λ ())
tyEqT LocatedThing Product = no (λ ())
tyEqT LocatedThing Maker = no (λ ())
tyEqT LocatedThing Place = no (λ ())
tyEqT LocatedThing LocatedThing = yes refl
tyEqT LocatedThing Causer = no (λ ())
tyEqT LocatedThing Result = no (λ ())
tyEqT LocatedThing Possessed = no (λ ())
tyEqT LocatedThing Possessor = no (λ ())
tyEqT Causer Container = no (λ ())
tyEqT Causer Content = no (λ ())
tyEqT Causer Creator = no (λ ())
tyEqT Causer Output = no (λ ())
tyEqT Causer Product = no (λ ())
tyEqT Causer Maker = no (λ ())
tyEqT Causer Place = no (λ ())
tyEqT Causer LocatedThing = no (λ ())
tyEqT Causer Causer = yes refl
tyEqT Causer Result = no (λ ())
tyEqT Causer Possessed = no (λ ())
tyEqT Causer Possessor = no (λ ())
tyEqT Result Container = no (λ ())
tyEqT Result Content = no (λ ())
tyEqT Result Creator = no (λ ())
tyEqT Result Output = no (λ ())
tyEqT Result Product = no (λ ())
tyEqT Result Maker = no (λ ())
tyEqT Result Place = no (λ ())
tyEqT Result LocatedThing = no (λ ())
tyEqT Result Causer = no (λ ())
tyEqT Result Result = yes refl
tyEqT Result Possessed = no (λ ())
tyEqT Result Possessor = no (λ ())
tyEqT Possessed Container = no (λ ())
tyEqT Possessed Content = no (λ ())
tyEqT Possessed Creator = no (λ ())
tyEqT Possessed Output = no (λ ())
tyEqT Possessed Product = no (λ ())
tyEqT Possessed Maker = no (λ ())
tyEqT Possessed Place = no (λ ())
tyEqT Possessed LocatedThing = no (λ ())
tyEqT Possessed Causer = no (λ ())
tyEqT Possessed Result = no (λ ())
tyEqT Possessed Possessed = yes refl
tyEqT Possessed Possessor = no (λ ())
tyEqT Possessor Container = no (λ ())
tyEqT Possessor Content = no (λ ())
tyEqT Possessor Creator = no (λ ())
tyEqT Possessor Output = no (λ ())
tyEqT Possessor Product = no (λ ())
tyEqT Possessor Maker = no (λ ())
tyEqT Possessor Place = no (λ ())
tyEqT Possessor LocatedThing = no (λ ())
tyEqT Possessor Causer = no (λ ())
tyEqT Possessor Result = no (λ ())
tyEqT Possessor Possessed = no (λ ())
tyEqT Possessor Possessor = yes refl

tyEqT-refl : ∀ X → tyEqT X X ≡ yes refl
tyEqT-refl Container = refl
tyEqT-refl Content = refl
tyEqT-refl Creator = refl
tyEqT-refl Output = refl
tyEqT-refl Product = refl
tyEqT-refl Maker = refl
tyEqT-refl Place = refl
tyEqT-refl LocatedThing = refl
tyEqT-refl Causer = refl
tyEqT-refl Result = refl
tyEqT-refl Possessed = refl
tyEqT-refl Possessor = refl

G : Graph
G = record
  { Ty     = T
  ; EdgeId = E
  ; src    = λ { e-contents → Container; e-output → Creator; e-maker → Product; e-located → Place; e-result → Causer; e-possessor → Possessed }
  ; tgt    = λ { e-contents → Content; e-output → Output; e-maker → Maker; e-located → LocatedThing; e-result → Result; e-possessor → Possessor }
  }

L : Lexicon
L = record
  { graph         = G
  ; tyEq          = tyEqT
  ; tyEq-refl     = tyEqT-refl
  ; PredId        = P
  ; ConstId       = K
  ; psig          = λ { p-ctxContainer → Container ∷ []; p-ctxContent → Content ∷ []; p-ctxCreator → Creator ∷ []; p-ctxOutput → Output ∷ []; p-ctxProduct → Product ∷ []; p-ctxMaker → Maker ∷ []; p-ctxPlace → Place ∷ []; p-ctxLocatedThing → LocatedThing ∷ []; p-ctxCauser → Causer ∷ []; p-ctxResult → Result ∷ []; p-ctxPossessed → Possessed ∷ []; p-ctxPossessor → Possessor ∷ [] }
  ; cty           = λ { c-targetContainer → Container; c-targetCreator → Creator; c-targetProduct → Product; c-targetPlace → Place; c-targetCauser → Causer; c-targetPossessed → Possessed }
  ; edgeOf         = λ { zero → just e-contents; (suc zero) → just e-output; (suc (suc zero)) → just e-maker; (suc (suc (suc zero))) → just e-located; (suc (suc (suc (suc zero)))) → just e-result; (suc (suc (suc (suc (suc zero))))) → just e-possessor; (suc (suc (suc (suc (suc (suc _)))))) → nothing }
  ; edgeName       = λ { e-contents → 0; e-output → 1; e-maker → 2; e-located → 3; e-result → 4; e-possessor → 5 }
  ; edgeOf-name    = λ { e-contents → refl; e-output → refl; e-maker → refl; e-located → refl; e-result → refl; e-possessor → refl }
  ; edgeOf-sound   = λ { zero e-contents _ → refl
                      ; zero e-output ()
                      ; zero e-maker ()
                      ; zero e-located ()
                      ; zero e-result ()
                      ; zero e-possessor ()
                      ; (suc zero) e-contents ()
                      ; (suc zero) e-output _ → refl
                      ; (suc zero) e-maker ()
                      ; (suc zero) e-located ()
                      ; (suc zero) e-result ()
                      ; (suc zero) e-possessor ()
                      ; (suc (suc zero)) e-contents ()
                      ; (suc (suc zero)) e-output ()
                      ; (suc (suc zero)) e-maker _ → refl
                      ; (suc (suc zero)) e-located ()
                      ; (suc (suc zero)) e-result ()
                      ; (suc (suc zero)) e-possessor ()
                      ; (suc (suc (suc zero))) e-contents ()
                      ; (suc (suc (suc zero))) e-output ()
                      ; (suc (suc (suc zero))) e-maker ()
                      ; (suc (suc (suc zero))) e-located _ → refl
                      ; (suc (suc (suc zero))) e-result ()
                      ; (suc (suc (suc zero))) e-possessor ()
                      ; (suc (suc (suc (suc zero)))) e-contents ()
                      ; (suc (suc (suc (suc zero)))) e-output ()
                      ; (suc (suc (suc (suc zero)))) e-maker ()
                      ; (suc (suc (suc (suc zero)))) e-located ()
                      ; (suc (suc (suc (suc zero)))) e-result _ → refl
                      ; (suc (suc (suc (suc zero)))) e-possessor ()
                      ; (suc (suc (suc (suc (suc zero))))) e-contents ()
                      ; (suc (suc (suc (suc (suc zero))))) e-output ()
                      ; (suc (suc (suc (suc (suc zero))))) e-maker ()
                      ; (suc (suc (suc (suc (suc zero))))) e-located ()
                      ; (suc (suc (suc (suc (suc zero))))) e-result ()
                      ; (suc (suc (suc (suc (suc zero))))) e-possessor _ → refl
                      ; (suc (suc (suc (suc (suc (suc k)))))) e-contents ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e-output ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e-maker ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e-located ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e-result ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e-possessor () }
  ; predOf         = λ { zero → just p-ctxContainer; (suc zero) → just p-ctxContent; (suc (suc zero)) → just p-ctxCreator; (suc (suc (suc zero))) → just p-ctxOutput; (suc (suc (suc (suc zero)))) → just p-ctxProduct; (suc (suc (suc (suc (suc zero))))) → just p-ctxMaker; (suc (suc (suc (suc (suc (suc zero)))))) → just p-ctxPlace; (suc (suc (suc (suc (suc (suc (suc zero))))))) → just p-ctxLocatedThing; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) → just p-ctxCauser; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) → just p-ctxResult; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) → just p-ctxPossessed; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) → just p-ctxPossessor; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc _)))))))))))) → nothing }
  ; predName       = λ { p-ctxContainer → 0; p-ctxContent → 1; p-ctxCreator → 2; p-ctxOutput → 3; p-ctxProduct → 4; p-ctxMaker → 5; p-ctxPlace → 6; p-ctxLocatedThing → 7; p-ctxCauser → 8; p-ctxResult → 9; p-ctxPossessed → 10; p-ctxPossessor → 11 }
  ; predOf-name    = λ { p-ctxContainer → refl; p-ctxContent → refl; p-ctxCreator → refl; p-ctxOutput → refl; p-ctxProduct → refl; p-ctxMaker → refl; p-ctxPlace → refl; p-ctxLocatedThing → refl; p-ctxCauser → refl; p-ctxResult → refl; p-ctxPossessed → refl; p-ctxPossessor → refl }
  ; predOf-sound   = λ { zero p-ctxContainer _ → refl
                      ; zero p-ctxContent ()
                      ; zero p-ctxCreator ()
                      ; zero p-ctxOutput ()
                      ; zero p-ctxProduct ()
                      ; zero p-ctxMaker ()
                      ; zero p-ctxPlace ()
                      ; zero p-ctxLocatedThing ()
                      ; zero p-ctxCauser ()
                      ; zero p-ctxResult ()
                      ; zero p-ctxPossessed ()
                      ; zero p-ctxPossessor ()
                      ; (suc zero) p-ctxContainer ()
                      ; (suc zero) p-ctxContent _ → refl
                      ; (suc zero) p-ctxCreator ()
                      ; (suc zero) p-ctxOutput ()
                      ; (suc zero) p-ctxProduct ()
                      ; (suc zero) p-ctxMaker ()
                      ; (suc zero) p-ctxPlace ()
                      ; (suc zero) p-ctxLocatedThing ()
                      ; (suc zero) p-ctxCauser ()
                      ; (suc zero) p-ctxResult ()
                      ; (suc zero) p-ctxPossessed ()
                      ; (suc zero) p-ctxPossessor ()
                      ; (suc (suc zero)) p-ctxContainer ()
                      ; (suc (suc zero)) p-ctxContent ()
                      ; (suc (suc zero)) p-ctxCreator _ → refl
                      ; (suc (suc zero)) p-ctxOutput ()
                      ; (suc (suc zero)) p-ctxProduct ()
                      ; (suc (suc zero)) p-ctxMaker ()
                      ; (suc (suc zero)) p-ctxPlace ()
                      ; (suc (suc zero)) p-ctxLocatedThing ()
                      ; (suc (suc zero)) p-ctxCauser ()
                      ; (suc (suc zero)) p-ctxResult ()
                      ; (suc (suc zero)) p-ctxPossessed ()
                      ; (suc (suc zero)) p-ctxPossessor ()
                      ; (suc (suc (suc zero))) p-ctxContainer ()
                      ; (suc (suc (suc zero))) p-ctxContent ()
                      ; (suc (suc (suc zero))) p-ctxCreator ()
                      ; (suc (suc (suc zero))) p-ctxOutput _ → refl
                      ; (suc (suc (suc zero))) p-ctxProduct ()
                      ; (suc (suc (suc zero))) p-ctxMaker ()
                      ; (suc (suc (suc zero))) p-ctxPlace ()
                      ; (suc (suc (suc zero))) p-ctxLocatedThing ()
                      ; (suc (suc (suc zero))) p-ctxCauser ()
                      ; (suc (suc (suc zero))) p-ctxResult ()
                      ; (suc (suc (suc zero))) p-ctxPossessed ()
                      ; (suc (suc (suc zero))) p-ctxPossessor ()
                      ; (suc (suc (suc (suc zero)))) p-ctxContainer ()
                      ; (suc (suc (suc (suc zero)))) p-ctxContent ()
                      ; (suc (suc (suc (suc zero)))) p-ctxCreator ()
                      ; (suc (suc (suc (suc zero)))) p-ctxOutput ()
                      ; (suc (suc (suc (suc zero)))) p-ctxProduct _ → refl
                      ; (suc (suc (suc (suc zero)))) p-ctxMaker ()
                      ; (suc (suc (suc (suc zero)))) p-ctxPlace ()
                      ; (suc (suc (suc (suc zero)))) p-ctxLocatedThing ()
                      ; (suc (suc (suc (suc zero)))) p-ctxCauser ()
                      ; (suc (suc (suc (suc zero)))) p-ctxResult ()
                      ; (suc (suc (suc (suc zero)))) p-ctxPossessed ()
                      ; (suc (suc (suc (suc zero)))) p-ctxPossessor ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxContainer ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxContent ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxCreator ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxOutput ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxProduct ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxMaker _ → refl
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxPlace ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxCauser ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxResult ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxPossessed ()
                      ; (suc (suc (suc (suc (suc zero))))) p-ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxPlace _ → refl
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p-ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxLocatedThing _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p-ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxCauser _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p-ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxResult _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p-ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxPossessed _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p-ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p-ctxPossessor _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p-ctxPossessor () }
  ; constOf        = λ { zero → just c-targetContainer; (suc zero) → just c-targetCreator; (suc (suc zero)) → just c-targetProduct; (suc (suc (suc zero))) → just c-targetPlace; (suc (suc (suc (suc zero)))) → just c-targetCauser; (suc (suc (suc (suc (suc zero))))) → just c-targetPossessed; (suc (suc (suc (suc (suc (suc _)))))) → nothing }
  ; constName      = λ { c-targetContainer → 0; c-targetCreator → 1; c-targetProduct → 2; c-targetPlace → 3; c-targetCauser → 4; c-targetPossessed → 5 }
  ; constOf-name   = λ { c-targetContainer → refl; c-targetCreator → refl; c-targetProduct → refl; c-targetPlace → refl; c-targetCauser → refl; c-targetPossessed → refl }
  ; constOf-sound  = λ { zero c-targetContainer _ → refl
                      ; zero c-targetCreator ()
                      ; zero c-targetProduct ()
                      ; zero c-targetPlace ()
                      ; zero c-targetCauser ()
                      ; zero c-targetPossessed ()
                      ; (suc zero) c-targetContainer ()
                      ; (suc zero) c-targetCreator _ → refl
                      ; (suc zero) c-targetProduct ()
                      ; (suc zero) c-targetPlace ()
                      ; (suc zero) c-targetCauser ()
                      ; (suc zero) c-targetPossessed ()
                      ; (suc (suc zero)) c-targetContainer ()
                      ; (suc (suc zero)) c-targetCreator ()
                      ; (suc (suc zero)) c-targetProduct _ → refl
                      ; (suc (suc zero)) c-targetPlace ()
                      ; (suc (suc zero)) c-targetCauser ()
                      ; (suc (suc zero)) c-targetPossessed ()
                      ; (suc (suc (suc zero))) c-targetContainer ()
                      ; (suc (suc (suc zero))) c-targetCreator ()
                      ; (suc (suc (suc zero))) c-targetProduct ()
                      ; (suc (suc (suc zero))) c-targetPlace _ → refl
                      ; (suc (suc (suc zero))) c-targetCauser ()
                      ; (suc (suc (suc zero))) c-targetPossessed ()
                      ; (suc (suc (suc (suc zero)))) c-targetContainer ()
                      ; (suc (suc (suc (suc zero)))) c-targetCreator ()
                      ; (suc (suc (suc (suc zero)))) c-targetProduct ()
                      ; (suc (suc (suc (suc zero)))) c-targetPlace ()
                      ; (suc (suc (suc (suc zero)))) c-targetCauser _ → refl
                      ; (suc (suc (suc (suc zero)))) c-targetPossessed ()
                      ; (suc (suc (suc (suc (suc zero))))) c-targetContainer ()
                      ; (suc (suc (suc (suc (suc zero))))) c-targetCreator ()
                      ; (suc (suc (suc (suc (suc zero))))) c-targetProduct ()
                      ; (suc (suc (suc (suc (suc zero))))) c-targetPlace ()
                      ; (suc (suc (suc (suc (suc zero))))) c-targetCauser ()
                      ; (suc (suc (suc (suc (suc zero))))) c-targetPossessed _ → refl
                      ; (suc (suc (suc (suc (suc (suc k)))))) c-targetContainer ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c-targetCreator ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c-targetProduct ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c-targetPlace ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c-targetCauser ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c-targetPossessed () }
  }

open Routes G

-- No declared equivalences in v1: the rule set is empty.
R : Rules G
R = record
  { RuleId = Ru
  ; rsrc   = λ ()
  ; rtgt   = λ ()
  ; lhs    = λ ()
  ; rhs    = λ ()
  }

ruleOfN : ℕ → Maybe Ru
ruleOfN _ = nothing
