{-# OPTIONS --safe --cubical --guardedness -WnoUnsupportedIndexedMatch #-}

-- GENERATED by pipeline/gen_agda.py. Do not edit by hand.
-- The uniform one-element snapshot for ConMeC: every sort has one element, every coercion relates it to
-- itself and every unary predicate holds of it. Acceptance against this snapshot checks the type and
-- route structure of a certificate against the lexicon, NOT the truth of the sentence (no external KB).
module Metonymy.ConMeCSnap where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Nat using (ℕ ; zero ; suc)
open import Cubical.Data.Bool using (Bool ; true ; false)
import Cubical.Data.FinData as F
open import Cubical.Data.FinData using (Fin ; discreteFin)
open import Cubical.Data.List using (List ; [] ; _∷_ ; map)
open import Cubical.Data.Sigma
import Cubical.Data.Empty as E
open import Agda.Builtin.Maybe

open import Metonymy.ConMeCKB
open import Metonymy.Check
open import Metonymy.Audit G R
open import Metonymy.Semantics G R using (SoundRules)
import Metonymy.Evidence L R as Ev
import Metonymy.Cert L R ruleOfN as Ct
import Metonymy.NormalizeFull L R as NF

sz : T → ℕ
sz _ = 1

allFin : (n : ℕ) → List (Fin n)
allFin zero    = []
allFin (suc n) = F.zero ∷ map F.suc (allFin n)

private
  memMap : ∀ {n} {xs : List (Fin n)} {x : Fin n} → Mem x xs → Mem (F.suc x) (map F.suc xs)
  memMap here      = here
  memMap (there m) = there (memMap m)

allFin-complete : ∀ n (x : Fin n) → Mem x (allFin n)
allFin-complete zero    ()
allFin-complete (suc n) F.zero    = here
allFin-complete (suc n) (F.suc x) = there (memMap (allFin-complete n x))

fin : FinModel
fin = record
  { Elem           = λ A → Fin (sz A)
  ; elemEq         = λ A → discreteFin
  ; elems          = λ A → allFin (sz A)
  ; elems-complete = λ A x → allFin-complete (sz A) x
  ; tab            = λ e x y → true
  }

sr : SoundRules (toModel fin)
sr = audit-all fin (λ ())

kb : Ev.KB
kb = record
  { fin      = fin
  ; refC     = λ c → F.zero
  ; predTab  = λ p args → true
  ; unaryTab = λ p A y → true
  }

ne : ∀ ρ → NF.lhsN ρ ≡ [] → E.⊥
ne ()

module C = Ct.Cert kb sr ne

tag : Maybe C.Checked → ℕ
tag nothing                = 0
tag (just (C.cResolve _))  = 1
tag (just (C.cRetain _))   = 2
tag (just (C.cFamily _))   = 3
tag (just (C.cConjoin _))  = 4
tag (just (C.cThree _))    = 5
