{-# OPTIONS --safe --cubical-compatible #-}

-- GENERATED by pipeline/gen_agda.py from the lexicon JSON (ConMeC v1). Do not edit by hand.
-- The ConMeC v1 lexicon: 12 sorts, 6 coercion edges, 12 predicates, 6 constants, no declared equivalences.
module Metonymy.ConMeCKB where

open import Metonymy.Base
open import Metonymy.Graph
open import Metonymy.Check

data T : Set where Container Content Creator Output Product Maker Place LocatedThing Causer Result Possessed Possessor : T
data E : Set where e_contents e_output e_maker e_located e_result e_possessor : E
data P : Set where p_ctxContainer p_ctxContent p_ctxCreator p_ctxOutput p_ctxProduct p_ctxMaker p_ctxPlace p_ctxLocatedThing p_ctxCauser p_ctxResult p_ctxPossessed p_ctxPossessor : P
data K : Set where c_targetContainer c_targetCreator c_targetProduct c_targetPlace c_targetCauser c_targetPossessed : K
data Ru : Set where

tyEqT : (X Y : T) → Dec (X ≡ Y)
tyEqT Container Container = yes refl
tyEqT Container Content = no (λ ())
tyEqT Container Creator = no (λ ())
tyEqT Container Output = no (λ ())
tyEqT Container Product = no (λ ())
tyEqT Container Maker = no (λ ())
tyEqT Container Place = no (λ ())
tyEqT Container LocatedThing = no (λ ())
tyEqT Container Causer = no (λ ())
tyEqT Container Result = no (λ ())
tyEqT Container Possessed = no (λ ())
tyEqT Container Possessor = no (λ ())
tyEqT Content Container = no (λ ())
tyEqT Content Content = yes refl
tyEqT Content Creator = no (λ ())
tyEqT Content Output = no (λ ())
tyEqT Content Product = no (λ ())
tyEqT Content Maker = no (λ ())
tyEqT Content Place = no (λ ())
tyEqT Content LocatedThing = no (λ ())
tyEqT Content Causer = no (λ ())
tyEqT Content Result = no (λ ())
tyEqT Content Possessed = no (λ ())
tyEqT Content Possessor = no (λ ())
tyEqT Creator Container = no (λ ())
tyEqT Creator Content = no (λ ())
tyEqT Creator Creator = yes refl
tyEqT Creator Output = no (λ ())
tyEqT Creator Product = no (λ ())
tyEqT Creator Maker = no (λ ())
tyEqT Creator Place = no (λ ())
tyEqT Creator LocatedThing = no (λ ())
tyEqT Creator Causer = no (λ ())
tyEqT Creator Result = no (λ ())
tyEqT Creator Possessed = no (λ ())
tyEqT Creator Possessor = no (λ ())
tyEqT Output Container = no (λ ())
tyEqT Output Content = no (λ ())
tyEqT Output Creator = no (λ ())
tyEqT Output Output = yes refl
tyEqT Output Product = no (λ ())
tyEqT Output Maker = no (λ ())
tyEqT Output Place = no (λ ())
tyEqT Output LocatedThing = no (λ ())
tyEqT Output Causer = no (λ ())
tyEqT Output Result = no (λ ())
tyEqT Output Possessed = no (λ ())
tyEqT Output Possessor = no (λ ())
tyEqT Product Container = no (λ ())
tyEqT Product Content = no (λ ())
tyEqT Product Creator = no (λ ())
tyEqT Product Output = no (λ ())
tyEqT Product Product = yes refl
tyEqT Product Maker = no (λ ())
tyEqT Product Place = no (λ ())
tyEqT Product LocatedThing = no (λ ())
tyEqT Product Causer = no (λ ())
tyEqT Product Result = no (λ ())
tyEqT Product Possessed = no (λ ())
tyEqT Product Possessor = no (λ ())
tyEqT Maker Container = no (λ ())
tyEqT Maker Content = no (λ ())
tyEqT Maker Creator = no (λ ())
tyEqT Maker Output = no (λ ())
tyEqT Maker Product = no (λ ())
tyEqT Maker Maker = yes refl
tyEqT Maker Place = no (λ ())
tyEqT Maker LocatedThing = no (λ ())
tyEqT Maker Causer = no (λ ())
tyEqT Maker Result = no (λ ())
tyEqT Maker Possessed = no (λ ())
tyEqT Maker Possessor = no (λ ())
tyEqT Place Container = no (λ ())
tyEqT Place Content = no (λ ())
tyEqT Place Creator = no (λ ())
tyEqT Place Output = no (λ ())
tyEqT Place Product = no (λ ())
tyEqT Place Maker = no (λ ())
tyEqT Place Place = yes refl
tyEqT Place LocatedThing = no (λ ())
tyEqT Place Causer = no (λ ())
tyEqT Place Result = no (λ ())
tyEqT Place Possessed = no (λ ())
tyEqT Place Possessor = no (λ ())
tyEqT LocatedThing Container = no (λ ())
tyEqT LocatedThing Content = no (λ ())
tyEqT LocatedThing Creator = no (λ ())
tyEqT LocatedThing Output = no (λ ())
tyEqT LocatedThing Product = no (λ ())
tyEqT LocatedThing Maker = no (λ ())
tyEqT LocatedThing Place = no (λ ())
tyEqT LocatedThing LocatedThing = yes refl
tyEqT LocatedThing Causer = no (λ ())
tyEqT LocatedThing Result = no (λ ())
tyEqT LocatedThing Possessed = no (λ ())
tyEqT LocatedThing Possessor = no (λ ())
tyEqT Causer Container = no (λ ())
tyEqT Causer Content = no (λ ())
tyEqT Causer Creator = no (λ ())
tyEqT Causer Output = no (λ ())
tyEqT Causer Product = no (λ ())
tyEqT Causer Maker = no (λ ())
tyEqT Causer Place = no (λ ())
tyEqT Causer LocatedThing = no (λ ())
tyEqT Causer Causer = yes refl
tyEqT Causer Result = no (λ ())
tyEqT Causer Possessed = no (λ ())
tyEqT Causer Possessor = no (λ ())
tyEqT Result Container = no (λ ())
tyEqT Result Content = no (λ ())
tyEqT Result Creator = no (λ ())
tyEqT Result Output = no (λ ())
tyEqT Result Product = no (λ ())
tyEqT Result Maker = no (λ ())
tyEqT Result Place = no (λ ())
tyEqT Result LocatedThing = no (λ ())
tyEqT Result Causer = no (λ ())
tyEqT Result Result = yes refl
tyEqT Result Possessed = no (λ ())
tyEqT Result Possessor = no (λ ())
tyEqT Possessed Container = no (λ ())
tyEqT Possessed Content = no (λ ())
tyEqT Possessed Creator = no (λ ())
tyEqT Possessed Output = no (λ ())
tyEqT Possessed Product = no (λ ())
tyEqT Possessed Maker = no (λ ())
tyEqT Possessed Place = no (λ ())
tyEqT Possessed LocatedThing = no (λ ())
tyEqT Possessed Causer = no (λ ())
tyEqT Possessed Result = no (λ ())
tyEqT Possessed Possessed = yes refl
tyEqT Possessed Possessor = no (λ ())
tyEqT Possessor Container = no (λ ())
tyEqT Possessor Content = no (λ ())
tyEqT Possessor Creator = no (λ ())
tyEqT Possessor Output = no (λ ())
tyEqT Possessor Product = no (λ ())
tyEqT Possessor Maker = no (λ ())
tyEqT Possessor Place = no (λ ())
tyEqT Possessor LocatedThing = no (λ ())
tyEqT Possessor Causer = no (λ ())
tyEqT Possessor Result = no (λ ())
tyEqT Possessor Possessed = no (λ ())
tyEqT Possessor Possessor = yes refl

tyEqT-refl : ∀ X → tyEqT X X ≡ yes refl
tyEqT-refl Container = refl
tyEqT-refl Content = refl
tyEqT-refl Creator = refl
tyEqT-refl Output = refl
tyEqT-refl Product = refl
tyEqT-refl Maker = refl
tyEqT-refl Place = refl
tyEqT-refl LocatedThing = refl
tyEqT-refl Causer = refl
tyEqT-refl Result = refl
tyEqT-refl Possessed = refl
tyEqT-refl Possessor = refl

G : Graph
G = record
  { Ty     = T
  ; EdgeId = E
  ; src    = λ { e_contents → Container; e_output → Creator; e_maker → Product; e_located → Place; e_result → Causer; e_possessor → Possessed }
  ; tgt    = λ { e_contents → Content; e_output → Output; e_maker → Maker; e_located → LocatedThing; e_result → Result; e_possessor → Possessor }
  }

L : Lexicon
L = record
  { graph         = G
  ; tyEq          = tyEqT
  ; tyEq-refl     = tyEqT-refl
  ; PredId        = P
  ; ConstId       = K
  ; psig          = λ { p_ctxContainer → Container ∷ []; p_ctxContent → Content ∷ []; p_ctxCreator → Creator ∷ []; p_ctxOutput → Output ∷ []; p_ctxProduct → Product ∷ []; p_ctxMaker → Maker ∷ []; p_ctxPlace → Place ∷ []; p_ctxLocatedThing → LocatedThing ∷ []; p_ctxCauser → Causer ∷ []; p_ctxResult → Result ∷ []; p_ctxPossessed → Possessed ∷ []; p_ctxPossessor → Possessor ∷ [] }
  ; cty           = λ { c_targetContainer → Container; c_targetCreator → Creator; c_targetProduct → Product; c_targetPlace → Place; c_targetCauser → Causer; c_targetPossessed → Possessed }
  ; edgeOf         = λ { zero → just e_contents; (suc zero) → just e_output; (suc (suc zero)) → just e_maker; (suc (suc (suc zero))) → just e_located; (suc (suc (suc (suc zero)))) → just e_result; (suc (suc (suc (suc (suc zero))))) → just e_possessor; (suc (suc (suc (suc (suc (suc _)))))) → nothing }
  ; edgeName       = λ { e_contents → 0; e_output → 1; e_maker → 2; e_located → 3; e_result → 4; e_possessor → 5 }
  ; edgeOf-name    = λ { e_contents → refl; e_output → refl; e_maker → refl; e_located → refl; e_result → refl; e_possessor → refl }
  ; edgeOf-sound   = λ { zero e_contents _ → refl
                      ; zero e_output ()
                      ; zero e_maker ()
                      ; zero e_located ()
                      ; zero e_result ()
                      ; zero e_possessor ()
                      ; (suc zero) e_contents ()
                      ; (suc zero) e_output _ → refl
                      ; (suc zero) e_maker ()
                      ; (suc zero) e_located ()
                      ; (suc zero) e_result ()
                      ; (suc zero) e_possessor ()
                      ; (suc (suc zero)) e_contents ()
                      ; (suc (suc zero)) e_output ()
                      ; (suc (suc zero)) e_maker _ → refl
                      ; (suc (suc zero)) e_located ()
                      ; (suc (suc zero)) e_result ()
                      ; (suc (suc zero)) e_possessor ()
                      ; (suc (suc (suc zero))) e_contents ()
                      ; (suc (suc (suc zero))) e_output ()
                      ; (suc (suc (suc zero))) e_maker ()
                      ; (suc (suc (suc zero))) e_located _ → refl
                      ; (suc (suc (suc zero))) e_result ()
                      ; (suc (suc (suc zero))) e_possessor ()
                      ; (suc (suc (suc (suc zero)))) e_contents ()
                      ; (suc (suc (suc (suc zero)))) e_output ()
                      ; (suc (suc (suc (suc zero)))) e_maker ()
                      ; (suc (suc (suc (suc zero)))) e_located ()
                      ; (suc (suc (suc (suc zero)))) e_result _ → refl
                      ; (suc (suc (suc (suc zero)))) e_possessor ()
                      ; (suc (suc (suc (suc (suc zero))))) e_contents ()
                      ; (suc (suc (suc (suc (suc zero))))) e_output ()
                      ; (suc (suc (suc (suc (suc zero))))) e_maker ()
                      ; (suc (suc (suc (suc (suc zero))))) e_located ()
                      ; (suc (suc (suc (suc (suc zero))))) e_result ()
                      ; (suc (suc (suc (suc (suc zero))))) e_possessor _ → refl
                      ; (suc (suc (suc (suc (suc (suc k)))))) e_contents ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e_output ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e_maker ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e_located ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e_result ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) e_possessor () }
  ; predOf         = λ { zero → just p_ctxContainer; (suc zero) → just p_ctxContent; (suc (suc zero)) → just p_ctxCreator; (suc (suc (suc zero))) → just p_ctxOutput; (suc (suc (suc (suc zero)))) → just p_ctxProduct; (suc (suc (suc (suc (suc zero))))) → just p_ctxMaker; (suc (suc (suc (suc (suc (suc zero)))))) → just p_ctxPlace; (suc (suc (suc (suc (suc (suc (suc zero))))))) → just p_ctxLocatedThing; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) → just p_ctxCauser; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) → just p_ctxResult; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) → just p_ctxPossessed; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) → just p_ctxPossessor; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc _)))))))))))) → nothing }
  ; predName       = λ { p_ctxContainer → 0; p_ctxContent → 1; p_ctxCreator → 2; p_ctxOutput → 3; p_ctxProduct → 4; p_ctxMaker → 5; p_ctxPlace → 6; p_ctxLocatedThing → 7; p_ctxCauser → 8; p_ctxResult → 9; p_ctxPossessed → 10; p_ctxPossessor → 11 }
  ; predOf-name    = λ { p_ctxContainer → refl; p_ctxContent → refl; p_ctxCreator → refl; p_ctxOutput → refl; p_ctxProduct → refl; p_ctxMaker → refl; p_ctxPlace → refl; p_ctxLocatedThing → refl; p_ctxCauser → refl; p_ctxResult → refl; p_ctxPossessed → refl; p_ctxPossessor → refl }
  ; predOf-sound   = λ { zero p_ctxContainer _ → refl
                      ; zero p_ctxContent ()
                      ; zero p_ctxCreator ()
                      ; zero p_ctxOutput ()
                      ; zero p_ctxProduct ()
                      ; zero p_ctxMaker ()
                      ; zero p_ctxPlace ()
                      ; zero p_ctxLocatedThing ()
                      ; zero p_ctxCauser ()
                      ; zero p_ctxResult ()
                      ; zero p_ctxPossessed ()
                      ; zero p_ctxPossessor ()
                      ; (suc zero) p_ctxContainer ()
                      ; (suc zero) p_ctxContent _ → refl
                      ; (suc zero) p_ctxCreator ()
                      ; (suc zero) p_ctxOutput ()
                      ; (suc zero) p_ctxProduct ()
                      ; (suc zero) p_ctxMaker ()
                      ; (suc zero) p_ctxPlace ()
                      ; (suc zero) p_ctxLocatedThing ()
                      ; (suc zero) p_ctxCauser ()
                      ; (suc zero) p_ctxResult ()
                      ; (suc zero) p_ctxPossessed ()
                      ; (suc zero) p_ctxPossessor ()
                      ; (suc (suc zero)) p_ctxContainer ()
                      ; (suc (suc zero)) p_ctxContent ()
                      ; (suc (suc zero)) p_ctxCreator _ → refl
                      ; (suc (suc zero)) p_ctxOutput ()
                      ; (suc (suc zero)) p_ctxProduct ()
                      ; (suc (suc zero)) p_ctxMaker ()
                      ; (suc (suc zero)) p_ctxPlace ()
                      ; (suc (suc zero)) p_ctxLocatedThing ()
                      ; (suc (suc zero)) p_ctxCauser ()
                      ; (suc (suc zero)) p_ctxResult ()
                      ; (suc (suc zero)) p_ctxPossessed ()
                      ; (suc (suc zero)) p_ctxPossessor ()
                      ; (suc (suc (suc zero))) p_ctxContainer ()
                      ; (suc (suc (suc zero))) p_ctxContent ()
                      ; (suc (suc (suc zero))) p_ctxCreator ()
                      ; (suc (suc (suc zero))) p_ctxOutput _ → refl
                      ; (suc (suc (suc zero))) p_ctxProduct ()
                      ; (suc (suc (suc zero))) p_ctxMaker ()
                      ; (suc (suc (suc zero))) p_ctxPlace ()
                      ; (suc (suc (suc zero))) p_ctxLocatedThing ()
                      ; (suc (suc (suc zero))) p_ctxCauser ()
                      ; (suc (suc (suc zero))) p_ctxResult ()
                      ; (suc (suc (suc zero))) p_ctxPossessed ()
                      ; (suc (suc (suc zero))) p_ctxPossessor ()
                      ; (suc (suc (suc (suc zero)))) p_ctxContainer ()
                      ; (suc (suc (suc (suc zero)))) p_ctxContent ()
                      ; (suc (suc (suc (suc zero)))) p_ctxCreator ()
                      ; (suc (suc (suc (suc zero)))) p_ctxOutput ()
                      ; (suc (suc (suc (suc zero)))) p_ctxProduct _ → refl
                      ; (suc (suc (suc (suc zero)))) p_ctxMaker ()
                      ; (suc (suc (suc (suc zero)))) p_ctxPlace ()
                      ; (suc (suc (suc (suc zero)))) p_ctxLocatedThing ()
                      ; (suc (suc (suc (suc zero)))) p_ctxCauser ()
                      ; (suc (suc (suc (suc zero)))) p_ctxResult ()
                      ; (suc (suc (suc (suc zero)))) p_ctxPossessed ()
                      ; (suc (suc (suc (suc zero)))) p_ctxPossessor ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxContainer ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxContent ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxCreator ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxOutput ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxProduct ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxMaker _ → refl
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxPlace ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxCauser ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxResult ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxPossessed ()
                      ; (suc (suc (suc (suc (suc zero))))) p_ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxPlace _ → refl
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc zero)))))) p_ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxLocatedThing _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc zero))))))) p_ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxCauser _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))) p_ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxResult _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))) p_ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxPossessed _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero)))))))))) p_ctxPossessor ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc zero))))))))))) p_ctxPossessor _ → refl
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxContainer ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxContent ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxCreator ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxOutput ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxProduct ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxMaker ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxPlace ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxLocatedThing ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxCauser ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxResult ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxPossessed ()
                      ; (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc (suc k)))))))))))) p_ctxPossessor () }
  ; constOf        = λ { zero → just c_targetContainer; (suc zero) → just c_targetCreator; (suc (suc zero)) → just c_targetProduct; (suc (suc (suc zero))) → just c_targetPlace; (suc (suc (suc (suc zero)))) → just c_targetCauser; (suc (suc (suc (suc (suc zero))))) → just c_targetPossessed; (suc (suc (suc (suc (suc (suc _)))))) → nothing }
  ; constName      = λ { c_targetContainer → 0; c_targetCreator → 1; c_targetProduct → 2; c_targetPlace → 3; c_targetCauser → 4; c_targetPossessed → 5 }
  ; constOf-name   = λ { c_targetContainer → refl; c_targetCreator → refl; c_targetProduct → refl; c_targetPlace → refl; c_targetCauser → refl; c_targetPossessed → refl }
  ; constOf-sound  = λ { zero c_targetContainer _ → refl
                      ; zero c_targetCreator ()
                      ; zero c_targetProduct ()
                      ; zero c_targetPlace ()
                      ; zero c_targetCauser ()
                      ; zero c_targetPossessed ()
                      ; (suc zero) c_targetContainer ()
                      ; (suc zero) c_targetCreator _ → refl
                      ; (suc zero) c_targetProduct ()
                      ; (suc zero) c_targetPlace ()
                      ; (suc zero) c_targetCauser ()
                      ; (suc zero) c_targetPossessed ()
                      ; (suc (suc zero)) c_targetContainer ()
                      ; (suc (suc zero)) c_targetCreator ()
                      ; (suc (suc zero)) c_targetProduct _ → refl
                      ; (suc (suc zero)) c_targetPlace ()
                      ; (suc (suc zero)) c_targetCauser ()
                      ; (suc (suc zero)) c_targetPossessed ()
                      ; (suc (suc (suc zero))) c_targetContainer ()
                      ; (suc (suc (suc zero))) c_targetCreator ()
                      ; (suc (suc (suc zero))) c_targetProduct ()
                      ; (suc (suc (suc zero))) c_targetPlace _ → refl
                      ; (suc (suc (suc zero))) c_targetCauser ()
                      ; (suc (suc (suc zero))) c_targetPossessed ()
                      ; (suc (suc (suc (suc zero)))) c_targetContainer ()
                      ; (suc (suc (suc (suc zero)))) c_targetCreator ()
                      ; (suc (suc (suc (suc zero)))) c_targetProduct ()
                      ; (suc (suc (suc (suc zero)))) c_targetPlace ()
                      ; (suc (suc (suc (suc zero)))) c_targetCauser _ → refl
                      ; (suc (suc (suc (suc zero)))) c_targetPossessed ()
                      ; (suc (suc (suc (suc (suc zero))))) c_targetContainer ()
                      ; (suc (suc (suc (suc (suc zero))))) c_targetCreator ()
                      ; (suc (suc (suc (suc (suc zero))))) c_targetProduct ()
                      ; (suc (suc (suc (suc (suc zero))))) c_targetPlace ()
                      ; (suc (suc (suc (suc (suc zero))))) c_targetCauser ()
                      ; (suc (suc (suc (suc (suc zero))))) c_targetPossessed _ → refl
                      ; (suc (suc (suc (suc (suc (suc k)))))) c_targetContainer ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c_targetCreator ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c_targetProduct ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c_targetPlace ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c_targetCauser ()
                      ; (suc (suc (suc (suc (suc (suc k)))))) c_targetPossessed () }
  }

open Routes G

-- No declared equivalences in v1: the rule set is empty.
R : Rules G
R = record
  { RuleId = Ru
  ; rsrc   = λ ()
  ; rtgt   = λ ()
  ; lhs    = λ ()
  ; rhs    = λ ()
  }

ruleOfN : ℕ → Maybe Ru
ruleOfN _ = nothing
