{-# OPTIONS --safe --cubical-compatible #-}

-- Syntactic layer of the formal core: the sense graph, routes (free category on the graph),
-- declared two-cells and the congruence they generate.
-- No cubical library imports here, so this layer stays compilable and is usable from cubical modules.
module Metonymy.Graph where

open import Agda.Builtin.Equality

-- Sense types and coercion edges (finite inventories in practice; identifiers are opaque).
record Graph : Set₁ where
  field
    Ty     : Set
    EdgeId : Set
    src    : EdgeId → Ty
    tgt    : EdgeId → Ty

module Routes (G : Graph) where
  open Graph G

  -- A route is a composable chain of edges; empty route at each type.
  data Route : Ty → Ty → Set where
    nil  : ∀ {A} → Route A A
    cons : ∀ (e : EdgeId) {C} → Route (tgt e) C → Route (src e) C

  infixr 5 _++_
  _++_ : ∀ {A B C} → Route A B → Route B C → Route A C
  nil       ++ s = s
  cons e r  ++ s = cons e (r ++ s)

  private
    cong-cons : ∀ {C} (e : EdgeId) {r r' : Route (tgt e) C} → r ≡ r' → cons e r ≡ cons e r'
    cong-cons e refl = refl

  ++-assoc : ∀ {A B C D} (p : Route A B) (q : Route B C) (r : Route C D)
           → (p ++ q) ++ r ≡ p ++ (q ++ r)
  ++-assoc nil        q r = refl
  ++-assoc (cons e p) q r = cong-cons e (++-assoc p q r)

  ++-unitʳ : ∀ {A B} (p : Route A B) → p ++ nil ≡ p
  ++-unitʳ nil        = refl
  ++-unitʳ (cons e p) = cong-cons e (++-unitʳ p)

-- Declared two-cells: each rule equates two parallel routes (an equivalence asserted by the lexicon).
record Rules (G : Graph) : Set₁ where
  open Graph G
  open Routes G
  field
    RuleId : Set
    rsrc   : RuleId → Ty
    rtgt   : RuleId → Ty
    lhs    : (ρ : RuleId) → Route (rsrc ρ) (rtgt ρ)
    rhs    : (ρ : RuleId) → Route (rsrc ρ) (rtgt ρ)

-- The congruence on routes generated by the rules (rewriting in arbitrary context).
module Equiv (G : Graph) (R : Rules G) where
  open Graph G
  open Routes G
  open Rules R

  infix 4 _≈_
  data _≈_ : ∀ {A B} → Route A B → Route A B → Set where
    ≈-refl  : ∀ {A B} {r : Route A B} → r ≈ r
    ≈-sym   : ∀ {A B} {r s : Route A B} → r ≈ s → s ≈ r
    ≈-trans : ∀ {A B} {r s t : Route A B} → r ≈ s → s ≈ t → r ≈ t
    ≈-step  : ∀ (ρ : RuleId) {A C} (p : Route A (rsrc ρ)) (s : Route (rtgt ρ) C)
            → (p ++ (lhs ρ ++ s)) ≈ (p ++ (rhs ρ ++ s))
