{-# OPTIONS --safe --cubical-compatible -WnoUnsupportedIndexedMatch #-}

-- GENERATED by pipeline/gen_agda.py from the lexicon JSON (Toponym v1). Do not edit by hand.
-- The Toponym v1 lexicon: 4 sorts, 4 coercion edges, 4 predicates, 0 constants, no declared equivalences.
module Metonymy.ToponymKB where

open import Metonymy.Base
open import Metonymy.Graph
open import Metonymy.Check

data T : Set where Place Polity Team People : T
data E : Set where e-exec e-legis e-team e-pop : E
data P : Set where p-reqPlace p-reqPolity p-reqTeam p-reqPeople : P

-- Constants are the places of the knowledge-base snapshot, numbered 0 .. 556-1.
data Fin : ℕ → Set where
  fz : ∀ {n} → Fin (suc n)
  fs : ∀ {n} → Fin n → Fin (suc n)

toNat : ∀ {n} → Fin n → ℕ
toNat fz     = 0
toNat (fs i) = suc (toNat i)

ofNat : (n : ℕ) → ℕ → Maybe (Fin n)
ofNat zero    _       = nothing
ofNat (suc n) zero    = just fz
ofNat (suc n) (suc m) = mapMaybe fs (ofNat n m)

ofNat-toNat : ∀ {n} (i : Fin n) → ofNat n (toNat i) ≡ just i
ofNat-toNat fz     = refl
ofNat-toNat (fs i) = cong (mapMaybe fs) (ofNat-toNat i)

predℕ : ℕ → ℕ
predℕ zero    = zero
predℕ (suc n) = n

ofNat-sound : ∀ n m (i : Fin n) → ofNat n m ≡ just i → toNat i ≡ m
ofNat-sound zero    m i ()
ofNat-sound (suc n) zero    fz     p = refl
ofNat-sound (suc n) zero    (fs i) ()
ofNat-sound (suc n) (suc m) fz     p with mapMaybe-just fs (ofNat n m) p
... | x , q , ()
ofNat-sound (suc n) (suc m) (fs i) p with mapMaybe-just fs (ofNat n m) p
... | x , q , r = cong suc (trans (sym (cong predℕ (cong toNat r))) (ofNat-sound n m x q))
data Ru : Set where

tyEqT : (X Y : T) → Dec (X ≡ Y)
tyEqT Place Place = yes refl
tyEqT Place Polity = no (λ ())
tyEqT Place Team = no (λ ())
tyEqT Place People = no (λ ())
tyEqT Polity Place = no (λ ())
tyEqT Polity Polity = yes refl
tyEqT Polity Team = no (λ ())
tyEqT Polity People = no (λ ())
tyEqT Team Place = no (λ ())
tyEqT Team Polity = no (λ ())
tyEqT Team Team = yes refl
tyEqT Team People = no (λ ())
tyEqT People Place = no (λ ())
tyEqT People Polity = no (λ ())
tyEqT People Team = no (λ ())
tyEqT People People = yes refl

tyEqT-refl : ∀ X → tyEqT X X ≡ yes refl
tyEqT-refl Place = refl
tyEqT-refl Polity = refl
tyEqT-refl Team = refl
tyEqT-refl People = refl

G : Graph
G = record
  { Ty     = T
  ; EdgeId = E
  ; src    = λ { e-exec → Place; e-legis → Place; e-team → Place; e-pop → Place }
  ; tgt    = λ { e-exec → Polity; e-legis → Polity; e-team → Team; e-pop → People }
  }

L : Lexicon
L = record
  { graph         = G
  ; tyEq          = tyEqT
  ; tyEq-refl     = tyEqT-refl
  ; PredId        = P
  ; ConstId       = Fin 556
  ; psig          = λ { p-reqPlace → Place ∷ []; p-reqPolity → Polity ∷ []; p-reqTeam → Team ∷ []; p-reqPeople → People ∷ [] }
  ; cty           = λ _ → Place
  ; edgeOf         = λ { zero → just e-exec; (suc zero) → just e-legis; (suc (suc zero)) → just e-team; (suc (suc (suc zero))) → just e-pop; (suc (suc (suc (suc _)))) → nothing }
  ; edgeName       = λ { e-exec → 0; e-legis → 1; e-team → 2; e-pop → 3 }
  ; edgeOf-name    = λ { e-exec → refl; e-legis → refl; e-team → refl; e-pop → refl }
  ; edgeOf-sound   = λ { zero e-exec _ → refl
                      ; zero e-legis ()
                      ; zero e-team ()
                      ; zero e-pop ()
                      ; (suc zero) e-exec ()
                      ; (suc zero) e-legis _ → refl
                      ; (suc zero) e-team ()
                      ; (suc zero) e-pop ()
                      ; (suc (suc zero)) e-exec ()
                      ; (suc (suc zero)) e-legis ()
                      ; (suc (suc zero)) e-team _ → refl
                      ; (suc (suc zero)) e-pop ()
                      ; (suc (suc (suc zero))) e-exec ()
                      ; (suc (suc (suc zero))) e-legis ()
                      ; (suc (suc (suc zero))) e-team ()
                      ; (suc (suc (suc zero))) e-pop _ → refl
                      ; (suc (suc (suc (suc k)))) e-exec ()
                      ; (suc (suc (suc (suc k)))) e-legis ()
                      ; (suc (suc (suc (suc k)))) e-team ()
                      ; (suc (suc (suc (suc k)))) e-pop () }
  ; predOf         = λ { zero → just p-reqPlace; (suc zero) → just p-reqPolity; (suc (suc zero)) → just p-reqTeam; (suc (suc (suc zero))) → just p-reqPeople; (suc (suc (suc (suc _)))) → nothing }
  ; predName       = λ { p-reqPlace → 0; p-reqPolity → 1; p-reqTeam → 2; p-reqPeople → 3 }
  ; predOf-name    = λ { p-reqPlace → refl; p-reqPolity → refl; p-reqTeam → refl; p-reqPeople → refl }
  ; predOf-sound   = λ { zero p-reqPlace _ → refl
                      ; zero p-reqPolity ()
                      ; zero p-reqTeam ()
                      ; zero p-reqPeople ()
                      ; (suc zero) p-reqPlace ()
                      ; (suc zero) p-reqPolity _ → refl
                      ; (suc zero) p-reqTeam ()
                      ; (suc zero) p-reqPeople ()
                      ; (suc (suc zero)) p-reqPlace ()
                      ; (suc (suc zero)) p-reqPolity ()
                      ; (suc (suc zero)) p-reqTeam _ → refl
                      ; (suc (suc zero)) p-reqPeople ()
                      ; (suc (suc (suc zero))) p-reqPlace ()
                      ; (suc (suc (suc zero))) p-reqPolity ()
                      ; (suc (suc (suc zero))) p-reqTeam ()
                      ; (suc (suc (suc zero))) p-reqPeople _ → refl
                      ; (suc (suc (suc (suc k)))) p-reqPlace ()
                      ; (suc (suc (suc (suc k)))) p-reqPolity ()
                      ; (suc (suc (suc (suc k)))) p-reqTeam ()
                      ; (suc (suc (suc (suc k)))) p-reqPeople () }
  ; constOf       = ofNat 556
  ; constName     = toNat
  ; constOf-name  = ofNat-toNat
  ; constOf-sound = ofNat-sound 556
  }

open Routes G

-- No declared equivalences in v1: the rule set is empty.
R : Rules G
R = record
  { RuleId = Ru
  ; rsrc   = λ ()
  ; rtgt   = λ ()
  ; lhs    = λ ()
  ; rhs    = λ ()
  }

ruleOfN : ℕ → Maybe Ru
ruleOfN _ = nothing
