{-# OPTIONS --safe --cubical-compatible #-}

-- GENERATED by pipeline/gen_agda.py from the lexicon JSON (Toponym v1). Do not edit by hand.
-- The Toponym v1 lexicon: 4 sorts, 4 coercion edges, 4 predicates, 1 constants, no declared equivalences.
module Metonymy.ToponymKB where

open import Metonymy.Base
open import Metonymy.Graph
open import Metonymy.Check

data T : Set where Place Polity Team People : T
data E : Set where e_exec e_legis e_team e_pop : E
data P : Set where p_reqPlace p_reqPolity p_reqTeam p_reqPeople : P
data K : Set where c_place : K
data Ru : Set where

tyEqT : (X Y : T) → Dec (X ≡ Y)
tyEqT Place Place = yes refl
tyEqT Place Polity = no (λ ())
tyEqT Place Team = no (λ ())
tyEqT Place People = no (λ ())
tyEqT Polity Place = no (λ ())
tyEqT Polity Polity = yes refl
tyEqT Polity Team = no (λ ())
tyEqT Polity People = no (λ ())
tyEqT Team Place = no (λ ())
tyEqT Team Polity = no (λ ())
tyEqT Team Team = yes refl
tyEqT Team People = no (λ ())
tyEqT People Place = no (λ ())
tyEqT People Polity = no (λ ())
tyEqT People Team = no (λ ())
tyEqT People People = yes refl

tyEqT-refl : ∀ X → tyEqT X X ≡ yes refl
tyEqT-refl Place = refl
tyEqT-refl Polity = refl
tyEqT-refl Team = refl
tyEqT-refl People = refl

G : Graph
G = record
  { Ty     = T
  ; EdgeId = E
  ; src    = λ { e_exec → Place; e_legis → Place; e_team → Place; e_pop → Place }
  ; tgt    = λ { e_exec → Polity; e_legis → Polity; e_team → Team; e_pop → People }
  }

L : Lexicon
L = record
  { graph         = G
  ; tyEq          = tyEqT
  ; tyEq-refl     = tyEqT-refl
  ; PredId        = P
  ; ConstId       = K
  ; psig          = λ { p_reqPlace → Place ∷ []; p_reqPolity → Polity ∷ []; p_reqTeam → Team ∷ []; p_reqPeople → People ∷ [] }
  ; cty           = λ { c_place → Place }
  ; edgeOf         = λ { zero → just e_exec; (suc zero) → just e_legis; (suc (suc zero)) → just e_team; (suc (suc (suc zero))) → just e_pop; (suc (suc (suc (suc _)))) → nothing }
  ; edgeName       = λ { e_exec → 0; e_legis → 1; e_team → 2; e_pop → 3 }
  ; edgeOf-name    = λ { e_exec → refl; e_legis → refl; e_team → refl; e_pop → refl }
  ; edgeOf-sound   = λ { zero e_exec _ → refl
                      ; zero e_legis ()
                      ; zero e_team ()
                      ; zero e_pop ()
                      ; (suc zero) e_exec ()
                      ; (suc zero) e_legis _ → refl
                      ; (suc zero) e_team ()
                      ; (suc zero) e_pop ()
                      ; (suc (suc zero)) e_exec ()
                      ; (suc (suc zero)) e_legis ()
                      ; (suc (suc zero)) e_team _ → refl
                      ; (suc (suc zero)) e_pop ()
                      ; (suc (suc (suc zero))) e_exec ()
                      ; (suc (suc (suc zero))) e_legis ()
                      ; (suc (suc (suc zero))) e_team ()
                      ; (suc (suc (suc zero))) e_pop _ → refl
                      ; (suc (suc (suc (suc k)))) e_exec ()
                      ; (suc (suc (suc (suc k)))) e_legis ()
                      ; (suc (suc (suc (suc k)))) e_team ()
                      ; (suc (suc (suc (suc k)))) e_pop () }
  ; predOf         = λ { zero → just p_reqPlace; (suc zero) → just p_reqPolity; (suc (suc zero)) → just p_reqTeam; (suc (suc (suc zero))) → just p_reqPeople; (suc (suc (suc (suc _)))) → nothing }
  ; predName       = λ { p_reqPlace → 0; p_reqPolity → 1; p_reqTeam → 2; p_reqPeople → 3 }
  ; predOf-name    = λ { p_reqPlace → refl; p_reqPolity → refl; p_reqTeam → refl; p_reqPeople → refl }
  ; predOf-sound   = λ { zero p_reqPlace _ → refl
                      ; zero p_reqPolity ()
                      ; zero p_reqTeam ()
                      ; zero p_reqPeople ()
                      ; (suc zero) p_reqPlace ()
                      ; (suc zero) p_reqPolity _ → refl
                      ; (suc zero) p_reqTeam ()
                      ; (suc zero) p_reqPeople ()
                      ; (suc (suc zero)) p_reqPlace ()
                      ; (suc (suc zero)) p_reqPolity ()
                      ; (suc (suc zero)) p_reqTeam _ → refl
                      ; (suc (suc zero)) p_reqPeople ()
                      ; (suc (suc (suc zero))) p_reqPlace ()
                      ; (suc (suc (suc zero))) p_reqPolity ()
                      ; (suc (suc (suc zero))) p_reqTeam ()
                      ; (suc (suc (suc zero))) p_reqPeople _ → refl
                      ; (suc (suc (suc (suc k)))) p_reqPlace ()
                      ; (suc (suc (suc (suc k)))) p_reqPolity ()
                      ; (suc (suc (suc (suc k)))) p_reqTeam ()
                      ; (suc (suc (suc (suc k)))) p_reqPeople () }
  ; constOf        = λ { zero → just c_place; (suc _) → nothing }
  ; constName      = λ { c_place → 0 }
  ; constOf-name   = λ { c_place → refl }
  ; constOf-sound  = λ { zero c_place _ → refl
                      ; (suc k) c_place () }
  }

open Routes G

-- No declared equivalences in v1: the rule set is empty.
R : Rules G
R = record
  { RuleId = Ru
  ; rsrc   = λ ()
  ; rtgt   = λ ()
  ; lhs    = λ ()
  ; rhs    = λ ()
  }

ruleOfN : ℕ → Maybe Ru
ruleOfN _ = nothing
